Add get sub groups to Admin API SDK
NikiforovAll/keycloak-authorization-services-dotnet pull request #143
Opened 2024-09-24 20:29 UTC by aron-666

2024-09-25 12:19 UTC, NikiforovAll requested changes
Thank you for the PR, let's work on some small things before we can merge it

2024-09-25 12:19 UTC, NikiforovAll commented on src/Keycloak.AuthServices.Sdk/Admin/IKeycloakGroupClient.cs
> +
nit: remove redundant spaces

2024-09-25 12:19 UTC, NikiforovAll commented on src/Keycloak.AuthServices.Sdk/Admin/KeycloakClient.cs
> +        var url = path + queryBuilder.ToQueryString();
do we need to ensure trailing '/' at the end of the path? Does it work?

2024-09-30 19:40 UTC, aron-666 commented on src/Keycloak.AuthServices.Sdk/Admin/KeycloakClient.cs
> +        var url = path + queryBuilder.ToQueryString();
No, I have tested it and it works.

2024-11-11 07:17 UTC, merged

2024-11-11 07:17 UTC, NikiforovAll commented
Thank you for the contribution