Roles / Claims Transformations: only add the roles once
NikiforovAll/keycloak-authorization-services-dotnet pull request #34
Opened 2023-04-03 20:06 UTC by JimHume

This avoids having an infinite number of roles get added to the ClaimsPrincipal when mapping the resource/realm access to roles.

This is in reference to https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/issues/33

2023-05-03 07:01 UTC, rasmus234 approved these changes

2023-05-23 12:10 UTC, NikiforovAll requested changes
Thank you for the MR. I'm looking forward to working on it with you.

2023-05-23 12:10 UTC, NikiforovAll commented on tests/Keycloak.AuthServices.Authentication.Tests/Usings.cs
> +global using Microsoft.VisualStudio.TestTools.UnitTesting;
What is the purpose of adding this global using?

2023-05-23 12:10 UTC, NikiforovAll commented on tests/Keycloak.AuthServices.Authentication.Tests/Claims/KeycloakRolesClaimsTransformationTests.cs
> +        foreach (var _ in Enumerable.Range(1, 3))
Let's change it to "for" loop style.

2023-05-23 12:10 UTC, NikiforovAll commented on tests/Keycloak.AuthServices.Authentication.Tests/Claims/KeycloakRolesClaimsTransformationTests.cs
> +    private const string MyResourceClaimValue = $"{{\u0022{MyAudience}\u0022:{{\u0022roles\u0022:[\u0022{MyFirstClaim}\u0022,\u0022{MySecondClaim}\u0022]}}}}";
Let's use regular double quote escaping to improve readability. $"\"x\"" or @"""x"""

2023-05-23 12:10 UTC, NikiforovAll commented on tests/Keycloak.AuthServices.Authentication.Tests/Keycloak.AuthServices.Authentication.Tests.csproj
> +    <PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
We don't really need this one. We are using XUnit as a default testing framework for this project.

2023-05-24 12:44 UTC, JimHume commented
All requested changes have been pushed.

2023-05-25 06:52 UTC, merged

2023-05-25 06:52 UTC, NikiforovAll commented
@JimHume  thank you for the contribution. I appreciate it 🙏